### ISSUE TITLE
BEdtools Error in TSV2VCF.py

### ISSUE THREAD

**Issue by caspargross** [imgag/umiVar_legacy#1]
Happened in multiple samples.  Covid. Maybe +1 error? Base offset by 1
```
[Traceback (most recent call last):
  File "/mnt/share/opt/cfdna_variant_caller/TSV2VCF.py", line 317, in <module>
    Seq_up, Seq_down = Up_Down_sequence(CHROM, POS, 6, args.reference)
  File "/mnt/share/opt/cfdna_variant_caller/TSV2VCF.py", line 54, in Up_Down_sequence
    a = a.sequence(fi=infile)
  File "/mnt/share/opt/miniconda3/envs/cfdna/lib/python3.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/mnt/share/opt/miniconda3/envs/cfdna/lib/python3.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/mnt/share/opt/miniconda3/envs/cfdna/lib/python3.7/site-packages/pybedtools/helpers.py", line 455, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools getfasta -fo /mnt/projects/research/20076C_0503_Virologie_HT/cfdna_tmp.mDlH/pybedtools.82p978x9.tmp -fi /mnt/share/data/genomes/GRCh38_MN908947.fa -bed /mnt/projects/research/20076C_0503_Virologie_HT/cfdna_tmp.mDlH/pybedtools.ihg_hcy1.tmp

Error message was:
Feature (MN908947.3:29899-29904) beyond the length of MN908947.3 size (29903 bp).  Skipping.
```

**Comment by caspargross** [comment]
Working directory: 
`/mnt/projects/research/20076C_0503_Virologie_HT`

Command lines:
```
    /mnt/share/opt/cfdna_variant_caller/cfdna_caller.sh         -bam Sample_20076a025_01/20076a025_01.bam         -o Sample_20076a025_01/20076a025_01.cfdna_var.vcf.gz         -b twist_sars_cov2.bed         -r /mnt/share/data/genomes/GRCh38_MN908947.fa         -ac 4 -str 0 -ns 1
    /mnt/share/opt/cfdna_variant_caller/cfdna_caller.sh         -bam Sample_20076a021_01/20076a021_01.bam         -o Sample_20076a021_01/20076a021_01.cfdna_var.vcf.gz         -b twist_sars_cov2.bed         -r /mnt/share/data/genomes/GRCh38_MN908947.fa         -ac 4 -str 0 -ns 1
    /mnt/share/opt/cfdna_variant_caller/cfdna_caller.sh         -bam Sample_20076a024_01/20076a024_01.bam         -o Sample_20076a024_01/20076a024_01.cfdna_var.vcf.gz         -b twist_sars_cov2.bed         -r /mnt/share/data/genomes/GRCh38_MN908947.fa         -ac 4 -str 0 -ns 1
    /mnt/share/opt/cfdna_variant_caller/cfdna_caller.sh         -bam Sample_20076Pos_01/20076Pos_01.bam         -o Sample_20076Pos_01/20076Pos_01.cfdna_var.vcf.gz         -b twist_sars_cov2.bed         -r /mnt/share/data/genomes/GRCh38_MN908947.fa         -ac 4 -str 0 -ns 1
    /mnt/share/opt/cfdna_variant_caller/cfdna_caller.sh         -bam Sample_20076a023_01/20076a023_01.bam         -o Sample_20076a023_01/20076a023_01.cfdna_var.vcf.gz         -b twist_sars_cov2.bed         -r /mnt/share/data/genomes/GRCh38_MN908947.fa         -ac 4 -str 0 -ns 1
````

Tmp folders created by the tool are still in the working dir
