### ISSUE TITLE
TypeError in pileup2tsv.py

### ISSUE THREAD

**Issue by caspargross** [imgag/umiVar_legacy#3]
Sample: `Sample_EX000019_01`

```
Traceback (most recent call last):
  File "/mnt/share/opt/cfdna_variant_caller/pileup2tsv.py", line 554, in <module>
    INFO = pileup_INFO(CHROM_POS)
  File "/mnt/share/opt/cfdna_variant_caller/pileup2tsv.py", line 252, in pileup_INFO
    del_quals_digit1, del_quals_digit2 = alt_qual_digit(del_observed, keep_base_quality, del_quals_digit1, del_quals_digit2)
  File "/mnt/share/opt/cfdna_variant_caller/pileup2tsv.py", line 30, in alt_qual_digit
    DIG1[variant.upper()].append(quality/10)
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by caspargross** [comment]
Also in Sample `Sample_EX000019_03`
